const booksflow=[
    {
        id: "1",
        Bookid:"1",
        Userid:"Петров",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "2",
        Bookid:"2",
        Userid:"Иванов",
        BookStatus:"зарезервирована",
        TimeStamp:"07.10.2021",
    },
    {
        id: "3",
        Bookid:"3",
        Userid:"Сидоров",
        BookStatus:"выдана",
        TimeStamp:"07.10.2021",
    },
    {
        id: "4",
        Bookid:"4",
        Userid:"4",
        BookStatus:"вернулась",
        TimeStamp:"07.10.2021",
    },
    {
        id: "5",
        Bookid:"5",
        Userid:"5",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "6",
        Bookid:"6",
        Userid:"6",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "7",
        Bookid:"7",
        Userid:"7",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "8",
        Bookid:"8",
        Userid:"8",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "9",
        Bookid:"9",
        Userid:"9",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "10",
        Bookid:"10",
        Userid:"10",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
    {
        id: "11",
        Bookid:"11",
        Userid:"11",
        BookStatus:"получена",
        TimeStamp:"07.10.2021",
    },
]
export default booksflow