const booksflow = [
    {
        id: "1",
        Bookid: "1",
        Userid: "1",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "2",
        Bookid: "2",
        Userid: "1",
        BookStatus: "Зарезервирована",
        TimeStamp: "07.10.2021",
    },
    {
        id: "3",
        Bookid: "3",
        Userid: "1",
        BookStatus: "Выдана",
        TimeStamp: "07.10.2021",
    },
    {
        id: "4",
        Bookid: "4",
        Userid: "2",
        BookStatus: "Вернулась",
        TimeStamp: "07.10.2021",
    },
    {
        id: "5",
        Bookid: "5",
        Userid: "2",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "6",
        Bookid: "6",
        Userid: "3",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "7",
        Bookid: "7",
        Userid: "3",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "8",
        Bookid: "8",
        Userid: "3",
        BookStatus: "получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "9",
        Bookid: "9",
        Userid: "1",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "10",
        Bookid: "10",
        Userid: "1",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
    {
        id: "11",
        Bookid: "2",
        Userid: "11",
        BookStatus: "Получена",
        TimeStamp: "07.10.2021",
    },
]
export default booksflow